### ISSUE TITLE
When referring to a person, consider using 'the app froze'

### ISSUE THREAD

**Issue by rillig** [errata-ai/alex#12]
Taken from Suicide.yml:
> When referring to a person, consider using 'the app froze or the app stopped responding or the app stopped responding to events or the app became unresponsive' instead of 'hang'.

Why would I ever call a person an app? The general message pattern doesn't make sense in this case.

**Comment by jdkato** [comment]
It looks like alex now uses the pattern "'...' may be insensitive, use ... instead."

In this case,

> 'hang' may be insensitive, use 'the app froze', 'the app stopped responding', 'the app stopped responding to events', 'the app became unresponsive' instead.

I'll update the rule to match.
