### ISSUE TITLE
Explain why suicide-related words are insensitive

### ISSUE THREAD

**Issue by rillig** [errata-ai/alex#13]
The file Suicide.yml only tells the rules but doesn't care to explain them. Without an explanation, rules tend to get misinterpreted, possibly leading to cargo-cult usage. To prevent this, all rules should be accompanied by an explanation, or at least a few further reading hints.

**Comment by jdkato** [comment]
See https://github.com/errata-ai/alex/issues/11#issuecomment-2438937923
